services:
  # Kibana
  kibana:
    image: kibana:9.0.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  # Elastic Search
  elasticsearch:
    image: elasticsearch:9.0.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
  
  # Mongo Db
  catalogdb:
    image: mongo
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
       
  # Redis Cache 
  basketdb:
    image: redis
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
        
  # RabbitMq
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 60s
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
        
  # Catalog Api
  catalog.api:
    image: catalogapi
    container_name: catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_URLS=http://+:80
      - "MongoDbSettings__ConnectionString=mongodb://catalogdb:27017"
      - "ElasticSettings__Uri=http://elasticsearch:9200"
    depends_on:
      - catalogdb
    ports:
      - 8080:80
      
  # Basket Api
  basket.api:
    image: basket.api
    container_name: basket.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_URLS=http://+:80
      - "MongoDbSettings__ConnectionString=mongodb://catalogdb:27017"
      - "ElasticSettings__Uri=http://elasticsearch:9200"
      - "RedisSettings__ConnectionString=basketdb"
      - "RabbitMq__ConnectionString=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - basketdb
      - rabbitmq
    ports: 
      - 8081:80
        
volumes:
  mongo_data:
  rabbitmq_data:
  elasticsearch-data: